### ISSUE TITLE
Test fails with latest wabt.js

### ISSUE THREAD

**Issue by marcusb** [GoogleChromeLabs/wasm-feature-detect#56]
Test failures when updating the wabt.js dependency to the latest [main branch](https://github.com/AssemblyScript/wabt.js/tree/v1.0.31-nightly.20221222).

```
~$ npm t

> wasm-feature-detect@1.3.0 test
> npm run fmt_test && npm run build && node --no-warnings test/index.js


> wasm-feature-detect@1.3.0 fmt_test
> prettier --check ./{,{src,rollup-plugins}/**/}*.{mjs,js,md}

Checking formatting...
All matched files use Prettier code style!

> wasm-feature-detect@1.3.0 build
> npm run build:library && npm run build:readme && npm run build:dts && npm run fmt


> wasm-feature-detect@1.3.0 build:library
> rollup -c


./src/index.js → dist/esm...
[!] (plugin at position 1) Error: Could not load ./src/index.js: parseWat failed:
/home/marcus/src/WebAssembly/wasm-feature-detect/src/detectors/reference-types/module.wat:7:5: error: opcode not allowed: ref.null
    ref.null func
    ^^^^^^^^

Error: Could not load ./src/index.js: parseWat failed:
/home/marcus/src/WebAssembly/wasm-feature-detect/src/detectors/reference-types/module.wat:7:5: error: opcode not allowed: ref.null
    ref.null func
    ^^^^^^^^

    at Object.parseWat (/home/marcus/src/WebAssembly/wasm-feature-detect/node_modules/wabt/index.js:28:26756)
    at compileWat (/home/marcus/src/WebAssembly/wasm-feature-detect/rollup.config.js:32:31)
    at /home/marcus/src/WebAssembly/wasm-feature-detect/rollup.config.js:91:19
    at async Promise.all (index 7)
    at Object.load (/home/marcus/src/WebAssembly/wasm-feature-detect/rollup.config.js:81:23)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
```

**Comment by marcusb** [comment]
Fixed with wabt.js 1.0.32.
